---

- import_tasks: restic-install.yml
  tags:
    - restic-install

- import_tasks: restic-script.yml
  when: restic_script_enabled
  tags:
    - restic-script

- import_tasks: restic-crontab.yml
  when: restic_script_enabled
  tags:
    - restic-crontab
