---

# daily backup
- name: crontab
  template:
    dest: /etc/cron.d/{{ restic_name }}-restic
    mode: u=rw,g=r,o=r
    src: restic-crontab
  when: "restic_crontab | default('', true) | length > 0"
