#! /bin/bash

THIS="$( readlink -f "${BASH_SOURCE[0]}" )"
DIR="$( dirname "$THIS" )"
check_script=check-repo

source "$DIR/check-restic-common"

restic check 2>&1 > "$OUTPUT_FILE"

if [ $? -eq 0 ]; then
  exit_clean_temp $OK
else
  exit_clean_temp $UNKNOWN
fi
