#! /bin/bash

OK=0
CRITICAL=2
UNKNOWN=3

if [ ! -r {{ restic_conf | quote }} ]; then
  echo "Configuration file "{{ restic_conf | quote }}" is missing"
  exit $UNKNOWN;
fi

source {{ restic_conf | quote }}

restic --no-lock check 2>&1

if [ $? -eq 0 ]; then
  exit 0
else
  # critical
  exit 2
fi
