#! /bin/bash

THIS="$( readlink -f "${BASH_SOURCE[0]}" )"
DIR="$( dirname "$THIS" )"
check_script=consistency

source "$DIR/check-restic-common"

ITERATION=5
CHECK_FILE="$MY_TEMP/check."
DIFF_FILE="$MY_TEMP/diff"
STDERR_FILE="$MY_TEMP/stderr"

if ! hash rclone &>/dev/null; then
  echo "rclone command is missing" > "${OUTPUT_FILE}"
  exit_clean_temp $UNKNOWN;
fi
if [ -z "${RCLONE_REPOSITORY}" ]; then
  echo "Missing repository name" > "${OUTPUT_FILE}"
  exit_clean_temp $UNKNOWN;
fi

>&2 echo "Checking ${RCLONE_REPOSITORY}"

if [ -z "$MY_TEMP" ]; then
  echo "Failure initializing temp directory" > "${OUTPUT_FILE}"
  exit_clean_temp "$UNKNOWN"
fi

if [ -n "$DEBUG" ]; then
  >&2 echo "Output to $MY_TEMP"
fi;

for i in $( seq $ITERATION ); do
  { rclone lsf --files-only -R ${RCLONE_REPOSITORY} | sort | uniq; } 1> "$CHECK_FILE$i" 2> "$STDERR_FILE"
  if [ ${PIPESTATUS[0]} -ne 0 ]; then
    echo "Error listing repository ${RCLONE_REPOSITORY}" > "${OUTPUT_FILE}"
    cat $STDERR_FILE > "${OUTPUT_FILE}"
    exit_clean_temp "$UNKNOWN"
  fi
done

status=0
for i in $( seq 2 $ITERATION); do
  diff -Nru "${CHECK_FILE}1" "${CHECK_FILE}$i" >> "$DIFF_FILE" 2>> "$STDERR_FILE"
  (( status = $? | $status ))
done

if [ $status -eq 0 ]; then
  echo "No inconsistency found in ${RCLONE_REPOSITORY}" > "${OUTPUT_FILE}"
elif [ $status -eq 1 ]; then
  echo "Inconsistencies found in ${RCLONE_REPOSITORY}" > "${OUTPUT_FILE}"
  cat "$DIFF_FILE" > "${OUTPUT_FILE}"
  status=$CRITICAL
else
  echo "Error comparing files" > "${OUTPUT_FILE}"
  cat "$STDERR_FILE" > "${OUTPUT_FILE}"
  status=$UNKNOWN
fi

exit_clean_temp $status
