#! /bin/bash

set -e

name={{ restic_name | quote }}
lock_file={{ restic_lock_file | quote }}
backuped_dir={{ restic_src | quote }}

restic_conf={{ restic_conf | quote }}

{% raw %}

if ! which restic > /dev/null || [ ! -x "$( which restic )" ]; then
  echo "FATAL - command restic not found"
  exit 1
fi

if ! lockfile-create --lock-name "${lock_file}"; then
  echo "FATAL - ${name} backup is currently locked"
  echo "FATAL - ensure that no ${name} backup is running and erase ${lock_file}"
  exit 1
fi
# run lockfile refresh in background process
lockfile-touch --lock-name "${lock_file}" &
lockfile_touch=$!

#
# Restic with remote object storage
#

source ${restic_conf}
restic backup "${backuped_dir}"
sleep 10
restic forget --keep-hourly 3 --keep-daily 7 --keep-weekly 5 --keep-monthly 12 --keep-yearly 75


# kill lockfile-touch process and remove lock
kill $lockfile_touch
lockfile-remove --lock-name "${lock_file}"

{% endraw %}
